' https://www.bilibili.com/video/BV1Fk4y1V7Lf/?p=4&vd_source=ccbe2dc08a135c5cfdb5c40bd777882a
' 2:50 ~ 3:50

@startuml 1
actor       二娃   as erwa 
actor       五娃    as wuwa  #Black
actor       六娃    as liuwa   #Purple
actor      蝙蝠精1  as bat1 #White
actor      蝙蝠精2  as bat2 #Yellow
entity     门外     as outside_of_the_door #Pink
entity     门内     as inside_of_the_door #Green
entity     葡萄     as grape1 #Orange
entity     葡萄     as grape2 #Orange



erwa -[#Grey]> wuwa : 告诉
note right
    兄弟们不好啦，
    大哥中了魔，
    被妖怪抓到啦，
    现在，
    妖怪把爷爷和大哥都关到十八层地洞中去了
end note

wuwa -[#Grey]> erwa :  告诉
note left: 大哥本领高强，力大无穷,怎么会被妖怪抓去了

liuwa -[#Grey]> erwa : 告诉
note right
    你再看看清楚
end note

erwa -[#Grey]> wuwa : 告诉
note right
    我这千里眼怎么会看错？
    妖怪有一个如意和一块魔镜，
    我得前去砸了他们的宝贝，
    才能救出爷爷和大哥。
end note

liuwa -[#Grey]> erwa : 告诉
note right: 二哥要小心

wuwa -[#Grey]> erwa : 告诉
note left: 二哥要小心

bat1 -[#Red]> outside_of_the_door : 飞到门外

erwa -[#Blue]> grape1 : 扔出

bat1 -[#Blue]> grape1 : 捡起

bat2 -[#Red]> outside_of_the_door : 飞到门外

erwa -[#Blue]> grape2 : 扔出

bat1 -[#Blue]> grape2 : 捡起

erwa -[#Yellow]> inside_of_the_door : 进入门内

bat1 -[#Green]> grape1 : 吃葡萄
bat1 -[#Green]> grape2 : 吃葡萄
bat2 -[#Orange]>bat2  : 流口水

@enduml

